In [1]:
import numpy as np

## Datatypes & Attributes

In [2]:
# numpy's main datatype is ndarray
a1= np.array([1,2,3])
a1

array([1, 2, 3])

In [3]:
type(a1)

numpy.ndarray

In [4]:
a2= np.array([[1,2.3,3.5],
              [4,5,6.7]])

a3= np.array([[[1,2,3],
              [4,5,6],
              [7,8,9]],
             [[10,11,12],
             [13,14,15],
             [16,17,18]]])

In [5]:
a2

array([[1. , 2.3, 3.5],
       [4. , 5. , 6.7]])

In [6]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [7]:
a1.shape

(3,)

In [8]:
a2.shape

(2, 3)

In [9]:
a3.shape

(2, 3, 3)

In [10]:
a1.ndim,a2.ndim,a3.ndim

(1, 2, 3)

In [11]:
a1.dtype,a2.dtype,a3.dtype

(dtype('int64'), dtype('float64'), dtype('int64'))

In [12]:
a1.size,a2.size,a3.size

(3, 6, 18)

In [13]:
type(a1),type(a2),type(a3)

(numpy.ndarray, numpy.ndarray, numpy.ndarray)

In [14]:
#creating a dataframe
import pandas as pd

df= pd.DataFrame(a2)
df

0    1    2
0  1.0  2.3  3.5
1  4.0  5.0  6.7

## 2.Create Numpy arrays

In [15]:
sample_array= np.array([1,2,3])
sample_array

array([1, 2, 3])

In [16]:
sample_array.dtype

dtype('int64')

In [17]:
ones= np.ones((2,3))
ones

array([[1., 1., 1.],
       [1., 1., 1.]])

In [18]:
ones.dtype

dtype('float64')

In [19]:
zeros= np.zeros((3,3))
zeros

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [20]:
range_array= np.arange(0,20,2)
range_array

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [21]:
random_array= np.random.randint(0,10,size=(3,5))
random_array

array([[4, 1, 8, 5, 7],
       [8, 0, 3, 6, 8],
       [0, 4, 6, 2, 6]])

In [22]:
random_array.size

15

In [23]:
random_array.shape

(3, 5)

In [24]:
np.random.random((5,3))

array([[0.33391085, 0.15595203, 0.19882745],
       [0.42433484, 0.60974332, 0.2340343 ],
       [0.41490394, 0.4363425 , 0.01427182],
       [0.27802674, 0.68003039, 0.38649501],
       [0.08331599, 0.5422977 , 0.10507038]])

In [25]:
random_array3= np.random.rand(5,3)
random_array3

array([[0.14097444, 0.64733742, 0.25325157],
       [0.80612218, 0.00713905, 0.29399029],
       [0.63655277, 0.00514212, 0.3492545 ],
       [0.13124729, 0.20763406, 0.08473526],
       [0.47992416, 0.80497438, 0.24561299]])

In [26]:
# psuedo random numbers
np.random.seed(seed=0)
random_array4= np.random.randint(10,size=(5,3))
random_array4

array([[5, 0, 3],
       [3, 7, 9],
       [3, 5, 2],
       [4, 7, 6],
       [8, 8, 1]])

In [27]:
random_array4.shape

(5, 3)

## 3.Viewing arrays and matrices

In [28]:
np.unique(random_array4)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [29]:
a1

array([1, 2, 3])

In [30]:
a2

array([[1. , 2.3, 3.5],
       [4. , 5. , 6.7]])

In [31]:
a3

array([[[ 1,  2,  3],
        [ 4,  5,  6],
        [ 7,  8,  9]],

       [[10, 11, 12],
        [13, 14, 15],
        [16, 17, 18]]])

In [32]:
a1[0]

1

In [33]:
a2[0]

array([1. , 2.3, 3.5])

In [34]:
a3.shape

(2, 3, 3)

In [35]:
a3[0]

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [36]:
a2[1]

array([4. , 5. , 6.7])

In [37]:
a3[:2,:2,:2]

array([[[ 1,  2],
        [ 4,  5]],

       [[10, 11],
        [13, 14]]])

In [38]:
a4= np.random.randint(10,size=(2,3,4,5))
a4

array([[[[6, 7, 7, 8, 1],
         [5, 9, 8, 9, 4],
         [3, 0, 3, 5, 0],
         [2, 3, 8, 1, 3]],

        [[3, 3, 7, 0, 1],
         [9, 9, 0, 4, 7],
         [3, 2, 7, 2, 0],
         [0, 4, 5, 5, 6]],

        [[8, 4, 1, 4, 9],
         [8, 1, 1, 7, 9],
         [9, 3, 6, 7, 2],
         [0, 3, 5, 9, 4]]],


       [[[4, 6, 4, 4, 3],
         [4, 4, 8, 4, 3],
         [7, 5, 5, 0, 1],
         [5, 9, 3, 0, 5]],

        [[0, 1, 2, 4, 2],
         [0, 3, 2, 0, 7],
         [5, 9, 0, 2, 7],
         [2, 9, 2, 3, 3]],

        [[2, 3, 4, 1, 2],
         [9, 1, 4, 6, 8],
         [2, 3, 0, 0, 6],
         [0, 6, 3, 3, 8]]]])